environment:

  matrix:

    # https://www.appveyor.com/docs/build-environment/#python

    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python311-x64"
    - PYTHON: "C:\\Python312-x64"
    - PYTHON: "C:\\Python313-x64"

install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover"
