version: 2

submodules:
  include: all

sphinx:
    builder: html
    configuration: docs/conf.py

python:
   install:
      - method: pip
        path: .
        extra_requirements: [all]
      - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
